gasto/urls.py
from django.urls import path
from .views import GastoCreateView, GastoListView, BuscaGastoListView, ExportarGastoView


gasto_urlpatterns = ([
    path('create',GastoCreateView.as_view(),name='create'),
    path('list',GastoListView.as_view(),name='list'),
    path('buscalist/<slug:mes>/<slug:ano>/',BuscaGastoListView.as_view(),name='buscalist'),
    path('gastolistado/<slug:mes>/<slug:ano>/',ExportarGastoView.as_view(),name='gastolistado'),
],'gasto')

gastos/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views
from gasto.urls import gasto_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeGastoView.as_view(), name='home'),
    path('gasto/',include(gasto_urlpatterns)),
    path('accounts/',include('django.contrib.auth.urls')),

]

core/models.py
from django.db import models

# Create your models here.

gasto/models.py
from django.db import models

# Create your models here.
class Gasto (models.Model):
    categoria = models.CharField(max_length=50)
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField()
    descripcion = models.TextField()

    def __str__(self):
        return self.descripcion
    
    class Meta:
        verbose_name = 'Gasto'
        verbose_name_plural = 'Gastos'
        ordering = ['-fecha']

gasto/forms.py
from django import forms
from gasto.models import Gasto

class GastoForm ( forms.ModelForm):
    class Meta:
        model = Gasto
        fields = ('categoria','importe','fecha','descripcion')
        widgets = {
            'fecha': forms.DateInput(format='%d%m%Y',attrs={'class':'form-control','type':'date'}),
            'descripcion': forms.TextInput(attrs={'class':'form-control'}),
            'importe': forms.NumberInput(attrs={'class':'form-control',}),
            'categoria': forms.TextInput(attrs={'class':'form-control'}),
        }
        labels = {
            'fecha': ' ',
            'descripcion': ' ',
            'importe': ' ',
            'categoria': ' ',
        }

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class HomeGastoView ( TemplateView ):
    template_name = 'core/home.html'

gasto/views.py
from datetime import datetime
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.db.models import Sum, Count
from .models import Gasto
from .forms import GastoForm
#imports👈 para pdf📄 export👉
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

# Create💡 your views🕶 here.🚩
class GastoCreateView(CreateView):
    model = Gasto
    form_class = GastoForm
    success_url = reverse_lazy('gasto:create')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)#Sobreescribimos el context para sumar mas data🤓
        context['categorias']= Gasto.objects.values('categoria').annotate(con_cat=Count('categoria')).filter(con_cat__gte=1).order_by('-con_cat')[0:3]
        context['categoriasdos']= Gasto.objects.values('categoria').annotate(con_catdos=Count('categoria')).filter(con_catdos__gte=1).order_by('-con_catdos')[3:]
        context['categoriastres']= Gasto.objects.values('categoria').annotate(con_cattres=Count('categoria')).filter(con_cattres__gte=1).order_by('-con_cattres')[7:]
        return context

class GastoListView(ListView):
    model = Gasto
    ordering = '-fecha'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mes = datetime.now().month
        ano = datetime.now().year
        context['total'] = Gasto.objects.filter(fecha__month=mes, fecha__year=ano).aggregate(total=Sum('importe'))['total']
        context['gasto'] = Gasto.objects.filter(fecha__month=mes, fecha__year=ano)
        meslista= {1:'Enero',2:'Febrero',3:'Marzo',4:'Abril',5:'Mayo',6:'Junio',7:'Julio',8:'Agosto',9:'Septiembre',10:'Octubre',11:'Noviembre',12:'Diciembre'}
        context['mes'] = meslista[mes]
        context['ano'] = ano
        return context
 

class BuscaGastoListView (ListView):
    model = Gasto
    ordering = '-fecha'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nromes={'Enero':'01','Febrero':'02','Marzo':'03','Abril':'04','Mayo':'05','Junio':'06',
        'Julio':'07','Agosto':'08','Septiembre':'09','Octubre':'10','Noviembre':'11','Diciembre':'12'}
        context['total'] = Gasto.objects.filter(fecha__month=nromes[self.kwargs['mes']], fecha__year=self.kwargs['ano']).aggregate(total=Sum('importe'))['total']
        context['gasto'] = Gasto.objects.filter(fecha__month=nromes[self.kwargs['mes']], fecha__year=self.kwargs['ano'])
        context['mes']= self.kwargs['mes']
        context['ano']= self.kwargs['ano']
        return context

class ExportarGastoView(View):
    def link_callback(self,uri, rel):
        """
        Convert HTML URIs to absolute system paths so xhtml2pdf can access those
        resources
        """
        result = finders.find(uri)
        if result:
                if not isinstance(result, (list, tuple)):
                        result = [result]
                result = list(os.path.realpath(path) for path in result)
                path=result[0]
        else:
                sUrl = settings.STATIC_URL        # Typically /static/
                sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
                mUrl = settings.MEDIA_URL         # Typically /media/
                mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

                if uri.startswith(mUrl):
                        path = os.path.join(mRoot, uri.replace(mUrl, ""))
                elif uri.startswith(sUrl):
                        path = os.path.join(sRoot, uri.replace(sUrl, ""))
                else:
                        return uri

        # make sure that file exists
        if not os.path.isfile(path):
                raise Exception(
                        'media URI must start with %s or %s' % (sUrl, mUrl)
                )
        return path

    def get(self, request, *args, **kwargs):
        meslistado = self.kwargs['mes']
        anolistado = self.kwargs['ano']
        template = get_template('gasto/gasto_listado.html')
        nromes={'Enero':'01','Febrero':'02','Marzo':'03','Abril':'04','Mayo':'05','Junio':'06',
        'Julio':'07','Agosto':'08','Septiembre':'09','Octubre':'10','Noviembre':'11','Diciembre':'12'}
        context = {
            'gastos': Gasto.objects.filter(fecha__month=nromes[meslistado], fecha__year=anolistado),
            'total': Gasto.objects.filter(fecha__month=nromes[self.kwargs['mes']], fecha__year=self.kwargs['ano']).aggregate(total=Sum('importe'))['total'],
            'mes': meslistado,
            'ano': anolistado,
            'title': 'Reporte de Gastos', 
        }
        html = template.render(context)
        response = HttpResponse(content_type='application/pdf')
        pisaStatus= pisa.CreatePDF(html,dest=response,link_callback=self.link_callback)
        return response

core/templates/core/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<nav class="navbar fixed-top bg-light">
    <div class="container-fluid">
    {% if not request.user.is_authenticated %}
      <a class="navbar-link" href="{% url 'login' %}"><button class="w-100 btn btn-sm btn-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-open-fill" viewBox="0 0 16 16">
        <path d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2h.5a.5.5 0 0 1 .5.5V15h-1V2zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
      </svg></button></a>
    {% else %}
      {{ request.user.username }}
      <a class="navbar-link" href="{% url 'logout' %}""><button class="w-100 btn btn-sm btn-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-closed-fill" viewBox="0 0 16 16">
        <path d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
      </svg></button></a>
    {% endif %}
    </div>
  </nav>

<body class=" bg-dark row align-items-center justify-content-center vh-100">
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'gasto/js/gasto.js' %}"></script>  
</body>
</html>

core/templates/core/home.html
{% extends "core/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if  request.user.is_authenticated %}
  <main>
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
          <form class="p-4 p-md-5 border rounded-3 bg-light">
            <a href="{% url 'gasto:create' %}"><button class="w-100 btn btn-lg btn-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg></button></a>
            <hr class="my-4">
            <a href="{% url 'gasto:list' %}">
            <div class=" row align-items-center justify-content-center">
              <button class="w-50 btn btn-sm btn-outline-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                  </svg></button>
            </div>
            </a>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endif%}
{% endblock %}
</html>

gasto/templates/gasto/gasto_form.html
{% extends "core/base.html" %}

{% block title %}Nuevo Gasto{% endblock %}

{% block content %}
{% if  request.user.is_authenticated %}
  <main>
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
          <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">{% csrf_token %}
            <a href="{% url 'home' %}">
            <div class=" row align-items-center justify-content-center mb-3">
              <button class="w-25 btn btn-sm btn-outline-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
              </svg></button>
            </div>
            </a>
            <div class="form-floating mb-3">
              {{ form.fecha }}
                <label for="id_fecha">Fecha</label>
                <!--<input type="date" class="form-control" id="floatingInput" placeholder="date">
                <label for="floatingInput">Fecha</label>-->
              </div>
              <div class="form-floating mb-3">
                {{ form.importe}}
                <label for="id_importe">Importe</label>
                <!--<input type="number" class="form-control" id="floatingInput" placeholder="number" value="0.00">
                <label for="floatingInput">Importe</label>-->
              </div>
              <div class="form-floating mb-3">
                {{ form.descripcion}}
                <label for="id_descripcion">Descripcion</label>
                <!--<input type="text" class="form-control" id="floatingInput" placeholder="Descripcion">
                <label for="floatingInput">Descripcion</label>-->
              </div>
              <div class="form-floating mb-3">
                {{ form.categoria }}
                <label for="id_categoria">Categoria</label>
                <!--<input type="text" class="form-control" id="floatingInput" placeholder="Categoria">
                <label for="floatingInput">Categoria</label>-->
              </div>
              <div class=" row align-items-center justify-content-center">
                <div class="btn-group btn-group" role="group" aria-label="...">
                  {% for cat in categorias %}
                    <button type="button" class="btn btn-outline-secondary nivelcategoria">{{ cat.categoria }}</button>
                  {% endfor %}
                </div>
                <div class="btn-group btn-group" role="group" aria-label="...">
                  {% for cat in categoriasdos %}
                    {% if forloop.counter < 5 %}
                      <button type="button" class="btn btn-sm btn-outline-secondary nivelcategoria">{{ cat.categoria }}</button>
                    {% endif %}
                  {% endfor %}
                </div>
                <div class="btn-group btn-group" role="group" aria-label="...">
                  {% for cat in categoriastres %}
                    {% if forloop.counter < 5 %}
                      <button type="button" class="btn btn-sm btn-outline-secondary nivelcategoria">{{ cat.categoria }}</button>
                    {% endif %}
                  {% endfor %}
                </div>
            </div>
            <br>
            <a href="{% url 'gasto:list' %}">
            <div class=" row align-items-center justify-content-center">
                <button class="w-50 btn btn-sm btn-outline-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                    <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                  </svg></button>
            </div>
            </a>
            <hr class="my-4">
            <button class="w-100 btn btn-lg btn-secondary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg></button>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endif %}
{% endblock %}

gasto/templates/gasto/gasto_list.html
{% extends "core/base.html" %}

{% block title %}Lista Gasto{% endblock %}


{% block content %}
  {% if  request.user.is_authenticated %}
  <main>
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        <div class="col-md-10 mx-auto col-lg-5">
          <form class="p-4 p-md-5 border rounded-3 bg-light">
            <a href="{% url 'home' %}">
              <div class=" row align-items-center justify-content-center mb-3">
                <button class="w-25 btn btn-sm btn-outline-secondary" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                </svg></button>
              </div>
              </a>
            <div class="input-group justify-content-center">
              <div class="col">
                  <select class="form-select" name="" id="selectmes" >
                      <option value="Enero">Enero</option>
                      <option value="Febrero">Febrero</option>
                      <option value="Marzo">Marzo</option>
                      <option value="Abril">Abril</option>
                      <option value="Mayo">Mayo</option>
                      <option value="Junio">Junio</option>
                      <option value="Julio">Julio</option>
                      <option value="Agosto">Agosto</option>
                      <option value="Septiembre">Septiembre</option>
                      <option value="Octubre">Octubre</option>
                      <option value="Noviembre">Noviembre</option>
                      <option value="Diciembre">Diciembre</option>
                  </select>
              </div>
              <div class="col">
                  <select class="form-select"  name="" id="selectano">
                      <option value="2020">2020</option>
                      <option value="2021">2021</option>
                      <option value="2022">2022</option>
                      <option value="2023">2023</option>
                      <option value="2024">2024</option>
                      <option value="2025">2025</option>
                      <option value="2026">2026</option>
                      <option value="2027">2027</option>
                      <option value="2028">2028</option>
                      <option value="2029">2029</option>
                      <option value="2030">2030</option>
                  </select>
              </div>
              <div class="align-items-center justify-content-center">
                <button class="w- btn btn-sm-block btn-outline-secondary" id="btnBuscarGasto" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg></button>
              </div>
              <div class="align-items-center justify-content-center">
                <button class="w- btn btn-sm-block btn-outline-secondary" id="btnPdfGasto" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-pdf" viewBox="0 0 16 16">
                  <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
                  <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"/>
                </svg></button>
              </div>
            </div>
            <hr class="my-4">
            <div class=" row align-items-center justify-content-center">
            <table class="table table-sm table-bordered ">
                <thead>
                  <th colspan="5" style="text-align: center;">{{mes}}-{{ano}}</th>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Descripcion</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Importe</th>
                  </tr>
                </thead>
                <tbody>
                  {% for g in gasto %}
                  <tr>
                    <th scope="row">{{ g.id}}</th>
                    <td>{{ g.fecha|date:"d/m/y" }}</td>
                    <td>{{ g.descripcion }}</td>
                    <td>{{ g.categoria }}</td>
                    <td>{{ g.importe }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <hr class="my-4">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingInput" placeholder="Total" value={{total }} disabled>
                <label for="floatingInput">Total:</label>
              </div>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endif %}
{% endblock %}

</html>

gasto/templates/gasto/gasto_listado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reporte</title>
    <style>
        body{
            font-family: Arial, Helvetica, sans-serif;
            padding:0;
            margin:0;
            color: black;
        }
        /* Tabla */
        table{
            width: 100%;
            border-collapse: collapse;
            border: 1px solid black;
        }
        thead th{
            border: 2px;
        }

        th, td{
            padding: 3px;
        }
        p{
           padding: 5px;
           text-align: left;
           font-size: 12px;
        }
        h1{
           padding: 5px;
           text-align: center;
           letter-spacing: 1px;
        }
    </style>
</head>
<body>
    <h1>{{title}}</h1>
    <p>Mes: {{mes}} -  Año: {{ano}}</p>
    <table>
        <thead>
            <tr>
                <th style="text-align: left;">Nro</th>
                <th>Fecha</th>
                <th>Descripcion</th>
                <th>Categoria</th>
                <th style="text-align: right;">Importe</th>
            </tr>
        </thead>
        <tbody>
            {% for gasto in gastos %}
                <tr>
                    <td style="text-align: left;">{{ gasto.id }}</td>
                    <td>{{ gasto.fecha }}</td>
                    <td>{{ gasto.descripcion }}</td>
                    <td>{{ gasto.categoria }}</td>
                    <td style="text-align: right;">{{ gasto.importe }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <p style="text-align: right;">Total: {{total}}</p>
</body>
</html>